### ISSUE TITLE
No redirect after enabling the plugin

### ISSUE THREAD

**Issue by ToniIltanen** [devopskube/redmine_openid_connect#1]
After installing and set the plugin settings and enabling it, the redmine's normal login screen is shown when logging in, the plugin does not forward the call to the openid connect provider instead.

**Comment by triplem** [comment]
Could you provide some detailed information, on the settings you provided? The Config is enabled?

Do you have access to the logs?

**Comment by ToniIltanen** [comment]
yeah, the config is enabled. Should the redirect happen from an custom url, or directly from the normal login page? /oic/login page tries to do something, but returns an error, which shows in the logs: 

`
Started GET "/oic/login" for 83.145.195.18 at 2017-11-07 16:49:38 +0000
Processing by AccountController#oic_login as HTML
  Current user: admin (id=1)
Completed 500 Internal Server Error in 492ms (ActiveRecord: 450.3ms)

NoMethodError (undefined method `+' for nil:NilClass):
  plugins/redmine_openid_connect/app/models/oic_session.rb:32:in `openid_configuration_url'
  plugins/redmine_openid_connect/app/models/oic_session.rb:40:in `block in get_dynamic_config'
  plugins/redmine_openid_connect/app/models/oic_session.rb:38:in `get_dynamic_config'
  plugins/redmine_openid_connect/app/models/oic_session.rb:45:in `dynamic_config'
  plugins/redmine_openid_connect/app/models/oic_session.rb:49:in `dynamic_config'
  plugins/redmine_openid_connect/app/models/oic_session.rb:152:in `authorization_url'
  plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:61:in `oic_login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

`

**Comment by triplem** [comment]
Uh, I will need to check this one. Hope to get it fixed.

**Comment by triplem** [comment]
Looks like a problem with variable assignments (using names instead of symbols). Just trying this now. Will be (most probably) some changes required.

**Comment by triplem** [comment]
0.9.3 should fix this issue, could you please confirm?

**Comment by ToniIltanen** [comment]
Redirect works now, thanks!
I'll start testing this plugin for furthermore now, i'll keep in touch if more issues comes along.
