### ISSUE TITLE
Redmine v4.0.0 support

### ISSUE THREAD

**Issue by SIkebe** [devopskube/redmine_openid_connect#19]
Which version of Redmine does this plugin support?
It already supports Redmine v4.0.0?

**Comment by ECOWOOD** [comment]
My environment is Redmine version 4.0.2.stable. We would like support by all means because we want to do SSO by OpenID Connect.

**Comment by ECOWOOD** [comment]
YES.

**Comment by joshocalico** [comment]
Try out my branch at #22. It seems to be working on my server.

**Comment by SIkebe** [comment]
@joshocalico Great! I'll try next week.

**Comment by ECOWOOD** [comment]
Thank you.

**Comment by Valeran86** [comment]
Hi, everyone! @joshocalico, thank you! 
It works for me in this environment:
```
Environment:
  Redmine version                4.0.3.devel
  Ruby version                   2.6.2-p47 (2019-03-13) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  redmine_openid_connect         0.9.4
```

**Comment by joshocalico** [comment]
I'm so glad to hear that things are working for you @Valeran86!
Hopefully changes can be merged in soon. Otherwise I might start a hard fork, got a few improvements I want to make 😄
