### ISSUE TITLE
Support for Keycloak

### ISSUE THREAD

**Issue by ataraxus** [devopskube/redmine_openid_connect#30]
Keycloak is currently a very popular IDP/IAM solution, it would be nice to have seamless support of its accesstoken structure, etc

**Comment by cheeZery** [comment]
We're using Keycloak and it works just fine ☺️ have you tried following [his guide](http://devopsku.be/setup/redmine-keycloak/)?

**Comment by ecswai201** [comment]
I have followed [this guide](http://devopsku.be/setup/redmine-keycloak/) ,but it didn't work ,can you help me

**Comment by ataraxus** [comment]
The current implementation works just fine. This Ticket could be closed actually.

@ecswai201 if you could provided more Info i might be able to help you. Especially Client config, error message and plugin settings would be nice. Please use Dummy data so you dont Exposé sensible data

**Comment by ecswai201** [comment]
> The current implementation works just fine. This Ticket could be closed actually.
> 
> @ecswai201 if you could provided more Info i might be able to help you. Especially Client config, error message and plugin settings would be nice. Please use Dummy data so you dont Exposé sensible data
I uploaded my config in this issue#75 ,

**Comment by ecswai201** [comment]
> We're using Keycloak and it works just fine ☺️ have you tried following [this guide](http://devopsku.be/setup/redmine-keycloak

What's your apps version?

**Comment by cheeZery** [comment]
> What's your apps version?

4.2.3.stable

**Comment by ecswai201** [comment]
> > What's your apps version?
> 
> 4.2.3.stable
 Can I see your keycloak and redmine configuration?

**Comment by xy795** [comment]
I hand an issue also with specifying the client scopes in Redmine.
Make sure you include the openid scope and separate multiple scopes ONLY with a ',', eg. `openid,prifile,email`

This resolved it for me.

**Comment by guoanhao** [comment]
> I hand an issue also with specifying the client scopes in Redmine. Make sure you include the openid scope and separate multiple scopes ONLY with a ',', eg. `openid,profile,email`
> 
> This resolved it for me.

thank you！I configured it the same way, but I still can't

![image](https://user-images.githubusercontent.com/50670492/218905109-698c9c56-fad0-4b7a-978e-feefc76ee111.png)
