### ISSUE TITLE
Redirects are not handled

### ISSUE THREAD

**Issue by ataraxus** [devopskube/redmine_openid_connect#35]
Feature Request. 
After IPD login one would expect that the site originally requested will show up. But this information is lost, after login. 
E.g. clicking on an issue from an email, one will be redirected to 'Home' instead of the issue initially clicked.

**Comment by ataraxus** [comment]
related issue: #17

**Comment by galupa** [comment]
Hi, I created this PR https://github.com/devopskube/redmine_openid_connect/pull/56 that should fix this issue
