### ISSUE TITLE
user_name is not a standard claim

### ISSUE THREAD

**Issue by ToniIltanen** [devopskube/redmine_openid_connect#4]
custom user_name scope is not based to the openid connect standard.
Insted, user_name should be changed to use **nickname** or **preferred_username** claims, and remove the scope from the query (both of these claims return inside the standard profile given through the id_token, without any additional scope request)

with these modifications, any standard openid connect provider should work by the book if the given username matches the requirements of redmine (no spaces etc). 

http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by triplem** [comment]
I guess, preferred_username should be it.

**Comment by triplem** [comment]
removed user_name from scope and use preferred_username as unique identifier of the user.
