### ISSUE TITLE
Admin Settings Available to all Users When Plugin Enabled

### ISSUE THREAD

**Issue by TonyWarner** [devopskube/redmine_openid_connect#47]
I'm using this plugin to authenticate into Redmine via Keycloack, but once enabled I'm seeing that non-admin users are able to access the `/admin` page by appending `/admin` to the hostname. Once on that page, they have read access to a majority of and both read and write access to several, of the admin settings. Pages, where they have read and write access, include, "Users" and all plugins.

I tested this with several different settings changes in both the plugin and within Keycloak and it has not alleviated the issue. 

Has anyone else had this same issue?

Application: [Docker Bitnami/Redmine 4.1.1](https://hub.docker.com/r/bitnami/redmine/) and [Docker Redmine 4.1.1](https://hub.docker.com/_/redmine)
Plugin Version: 0.9.4
IDP: Keycloak

**Comment by corybolar** [comment]
This should be fixed with #48

**Comment by triplem** [comment]
Closing, since #48 is already merged.
