### ISSUE TITLE
None of the alternative username fields are returned by Google OpenID

### ISSUE THREAD

**Issue by eirc** [devopskube/redmine_openid_connect#51]
I actually get an exception in the error handling code where it doesn't have a user login to display. But this all is due to the `user_info` not containing any of: `user_name`, `nickname` or `preferred_username` used at https://github.com/devopskube/redmine_openid_connect/blob/master/lib/redmine_openid_connect/account_controller_patch.rb#L96 as the login username.

A sample `user_info` object as returned by Google looks like this (I have replaced actual info with `<descriptions>`):

```
{
  "sub"=>"<SOME BIG NUMBER>",
  "name"=>"<FULL NAME>",
  "given_name"=>"<FIRST NAME>",
  "family_name"=>"<LAST NAME>",
  "profile"=>"https://plus.google.com/<SOME BIG NUMBER>",
  "picture"=>"https://lh3.googleusercontent.com/a-/<SOME BIG ID>",
  "email"=>"<EMAIL>",
  "email_verified"=>true,
  "locale"=>"en",
  "hd"=>"<MY DOMAIN>"
}
```

The actual error I get in the logs looks like this:

```
Started GET "/oic/local_login?state=<REDACTED>&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=<REDACTED>&prompt=none" fo
r <REDACTED> at 2021-02-09 14:41:44 +0000
Processing by AccountController#oic_local_login as HTML
  Parameters: {"state"=>"<REDACTED>", "code"=>"<REDACTED>", "scope"=>"email profile openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email", "authuser"=>"0", "hd"=>"<REDACTED>", "prompt"
=>"none"}
  Current user: anonymous
Completed 500 Internal Server Error in 229ms (ActiveRecord: 11.2ms)

I18n::MissingInterpolationArgument (missing interpolation argument :value in "Could no create the user %{value}: " ({:count=>nil} given)):

lib/redmine/i18n.rb:36:in `l'
plugins/redmine_openid_connect/lib/redmine_openid_connect/account_controller_patch.rb:128:in `oic_local_login'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

I've also tried different combinations of the `email`, `profile` and `openid` scopes in the settings (comma separated as mentioned next to the field).

I worked around this by adding an `|| user_info["email"]` at the of of the `.login = ` options but I have no idea if this causes any other unintended side effect hence I did not send a PR.

**Comment by triplem** [comment]
Sound reasonable to add this. A PR would be very much appreciated.
