### ISSUE TITLE
local_login?error=invalid_request&error_description=Invalid+scopes

### ISSUE THREAD

**Issue by Born2Bake** [devopskube/redmine_openid_connect#53]
Hi,

I wonder if this plugin is compatible with Keycloak 12.0.4 version?

I have followed that guide http://devopsku.be/setup/redmine-keycloak/ and some parts can't be configured the same way as on the screenshots in the guide.

https://prnt.sc/12f60oy - keycloak main setttings; https://prnt.sc/12f614j - roles ; https://prnt.sc/12f61lv - mappers ; https://prnt.sc/12f64rd - redmine configuration.

In scope tab, if Full Scope Allowed is enabled there is no other options you can set. If you disable it - https://prnt.sc/12f622e it can't be saved.

In the end, I am getting this - oic/local_login?error=invalid_request&error_description=Invalid+scopes%3A+&state=xxxxx and empty redmine page.

Can someone help and advice if there is other way to configure it correctly?

**Comment by acul009** [comment]
Hi,
I‘m having the same issue atm.
How did you solve it?

**Comment by guwq-dave** [comment]
I see this is closed but what worked for me was the following attributes in Redmine:

OpenID Connect scopes (comma-separated): openid,profile,email

Hope this helps somebody else as I myself was scratching my head.
