### ISSUE TITLE
oic_sessions table full

### ISSUE THREAD

**Issue by MaxWaldorf** [devopskube/redmine_openid_connect#58]
Hello,

I am facing this issue where the oic_session table is full in Mariadb...

I did on the table:
`ALTER TABLE oic_sessions MAX_ROWS=1000000 AVG_ROW_LENGTH=3276`

But I really don't know if this is a good thing to do...
Has anyone seen this? Is there a way to purge NULL sessions?

Cheers

**Comment by galupa** [comment]
Hi,

I actually have the same issue, have not really make the table full, but realized that the table is keep growing.
And we actually create a fix for this by removing old session from the current user every time they re-login.
Maybe I will create a PR for this.

Cheers

**Comment by galupa** [comment]
Just created this PR https://github.com/devopskube/redmine_openid_connect/pull/59
