### ISSUE TITLE
Login error invalid_scope

### ISSUE THREAD

**Issue by guoanhao** [devopskube/redmine_openid_connect#73]
keycloak version：19.0.3

Click Login to report an error：

`http://ip:8030/oic/local_login?error=invalid_scope&error_description=Invalid+scopes%3A+&state=21318a43-69f0-46fb-8df3-9cad122948fe`
![image](https://user-images.githubusercontent.com/50670492/207249279-878191ef-35e0-46fd-9ee8-24eb7a165535.png)

`Started GET "/oic/local_login?error=invalid_scope&error_description=Invalid+scopes%3A+&state=21318a43-69f0-46fb-8df3-9cad122948fe" for 10.249.3.45 at 2022-12-13 07:08:04 +0000
`

![image](https://user-images.githubusercontent.com/50670492/207249496-6ba399f3-0bf9-4aad-b23b-68e60e6bbfbb.png)

keyclock error:

`KC-SERVICES0093: Invalid parameter value for: scope`

redmine_openid_connect configuration：
![image](https://user-images.githubusercontent.com/50670492/207224594-07b5a8dd-3576-4eaa-a9b5-5d45c47f9858.png)

**Comment by guoanhao** [comment]
找到问题了，OpenID Connect scopes (comma-separated)要配置：openid

**Comment by triplem** [comment]
??

**Comment by guoanhao** [comment]
> ？？

![image](https://user-images.githubusercontent.com/50670492/208013474-36864a52-575e-4867-9add-716a71cc4126.png)
