### ISSUE TITLE
Invalid user name or password Try logging in with another account。Could not create the user admin：Email address cannot be empty characters First name cannot be empty characters Last name cannot be empty The login name has already been used

### ISSUE THREAD

**Issue by guoanhao** [devopskube/redmine_openid_connect#77]
![image](https://user-images.githubusercontent.com/50670492/215638076-4b83dc93-5da9-4493-8c49-6bfdda405147.png)

![image](https://user-images.githubusercontent.com/50670492/215637909-f31f2336-a649-4deb-826b-e88ea358c13b.png)

**Comment by Sik1a** [comment]
check the entry-point "user_info"  of your provider , it should contain the attributes mentioned in this code section bellow  , they are necessary for the creation of the new user 
![hey](https://user-images.githubusercontent.com/66503212/216345069-a958a599-68b6-49de-a6ce-0844fa008c46.PNG)

**Comment by guoanhao** [comment]
> 检查您的提供商的入口点“user_info”，它应该包含下面这段代码中提到的属性，它们是创建新用户所必需的 ![嘿](https://user-images.githubusercontent.com/66503212/216345069-a958a599-68b6-49de-a6ce-0844fa008c46.PNG)

thank you，These attributes are included in my code：
![image](https://user-images.githubusercontent.com/50670492/216493812-0a2e8062-470c-4d5d-8685-7b1d34017720.png)

mapper：
![image](https://user-images.githubusercontent.com/50670492/216494835-8477d951-f1aa-4abc-811e-76490c85dbad.png)

**Comment by Sik1a** [comment]
hi again :)  , i know that the attributes  are mentioned in the code but your provider must have the same attributes in the "USER-INFO" entry-point , and try to add email as a scope also next to openid and profile

**Comment by guoanhao** [comment]
> hi again :) , i know that the attributes are mentioned in the code but your provider must have the same attributes in the "USER-INFO" entry-point , and try to add email as a scope also next to openid and profile

Sorry, I don't understand what you mean. I don't know how to configure it. Would you please provide the configuration reference screenshot or configuration document? Thank you very much

**Comment by guoanhao** [comment]
> 请问是什么问题？ 谢谢 ！

Sorry, I don't know what the problem is. I configured it according to this manual：http://devopsku.be/setup/redmine-keycloak/

Redmine login can jump to keycloak：
![image](https://user-images.githubusercontent.com/50670492/217978992-3a7634c5-d8a2-4fe6-bb4e-ce6ad348cd72.png)

But the login report is wrong：
【invalid username or password [Try logging in with another account](http://ip:8030/logout)】
![image](https://user-images.githubusercontent.com/50670492/217979518-dbc46fa7-4a9c-4a3c-b09d-a9b0322aab9a.png)
【You have been logged out. [Click here to log in again](http://ip:8030/).】
![image](https://user-images.githubusercontent.com/50670492/217979444-e4c12f12-dc2e-47ee-8ff0-fb22a92242ae.png)

**Comment by guoanhao** [comment]
> can i ask what was the problem ? thank you !

Sorry, I don't know what the problem is. I configured it according to this manual：http://devopsku.be/setup/redmine-keycloak/

Redmine login can jump to keycloak：
![image](https://user-images.githubusercontent.com/50670492/217978992-3a7634c5-d8a2-4fe6-bb4e-ce6ad348cd72.png)

But the login report is wrong：
【invalid username or password [Try logging in with another account](http://ip:8030/logout)】
![image](https://user-images.githubusercontent.com/50670492/217979518-dbc46fa7-4a9c-4a3c-b09d-a9b0322aab9a.png)
【You have been logged out. [Click here to log in again](http://ip:8030/).】
![image](https://user-images.githubusercontent.com/50670492/217979444-e4c12f12-dc2e-47ee-8ff0-fb22a92242ae.png)

thank you ！

**Comment by zhangran2616** [comment]
> > can i ask what was the problem ? thank you !
> 
> Sorry, I don't know what the problem is. I configured it according to this manual：http://devopsku.be/setup/redmine-keycloak/
> 
> Redmine login can jump to keycloak： ![image](https://user-images.githubusercontent.com/50670492/217978992-3a7634c5-d8a2-4fe6-bb4e-ce6ad348cd72.png)
> 
> But the login report is wrong： 【invalid username or password [Try logging in with another account](http://ip:8030/logout)】 ![image](https://user-images.githubusercontent.com/50670492/217979518-dbc46fa7-4a9c-4a3c-b09d-a9b0322aab9a.png) 【You have been logged out. [Click here to log in again](http://ip:8030/).】 ![image](https://user-images.githubusercontent.com/50670492/217979444-e4c12f12-dc2e-47ee-8ff0-fb22a92242ae.png)
> 
> thank you ！

问题解决了吗？可以登录了吗？
